# Generated by Django 3.1.3 on 2023-08-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230802_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprofile',
            name='lastGiven',
            field=models.DateField(default='2000-08-02'),
        ),
    ]
