# Generated by Django 3.1.3 on 2023-08-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20230802_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprofile',
            name='totalDonate',
            field=models.IntegerField(default=0),
        ),
    ]
