# Generated by Django 3.1.3 on 2023-08-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20230802_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], default='A+', max_length=3)),
                ('type', models.CharField(choices=[('Emergency', 'Emergency'), ('Managed', 'Managed')], default='Emergency', max_length=10)),
                ('phoneNum', models.BigIntegerField(default=880)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.aprofile')),
                ('reqForDonate', models.ManyToManyField(blank=True, default=None, related_name='requestForDonate', to='profiles.Aprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.arequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.aprofile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
