# Generated by Django 3.1.3 on 2023-08-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arequest',
            name='title',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
