# Generated by Django 3.1.3 on 2023-08-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20230802_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='arequest',
            name='bag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='arequest',
            name='location',
            field=models.CharField(default='Dhaka Medical Hospital', max_length=100),
        ),
    ]
